apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
# obviously in a real situation this is not to be commited to a code versionning software
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==