require 'fileutils'


# Create shared_folder directory if it doesn't exist
FileUtils.mkdir_p 'shared_folder' unless File.exist?('shared_folder')

# ---------------------------------------------------------------------------- #
#                                    DEFINES                                   #
# ---------------------------------------------------------------------------- #

SERVER_NODE_NAME = "jereverdS"
SERVER_NODE_IP = "192.168.56.110"
MEMORY = "2048"
CPUS = "1"

# ---------------------------------------------------------------------------- #
#                                   VM CONFIG                                  #
# ---------------------------------------------------------------------------- #

Vagrant.configure("2") do |config|

  
  config.vm.box = "bento/debian-12"
  config.vm.synced_folder "shared_folder", "/shared_folder", create: true
  
  # ----------------------------------- server ----------------------------------- #
  
  config.vm.define SERVER_NODE_NAME do |server|
    server.vm.hostname = SERVER_NODE_NAME
    server.vm.network "private_network", ip: SERVER_NODE_IP
    server.vm.provider "virtualbox" do |vb|
      vb.memory = MEMORY
      vb.cpus = CPUS
    end
  
    # ---------------------------- k3s installation script --------------------------- #
  
    server.vm.provision "shell", inline: 
    <<-SHELL
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --write-kubeconfig-mode 644 --node-ip=#{SERVER_NODE_IP}" sh -s -
      kubectl apply -f /vagrant/webapp/webapp.yaml
      kubectl apply -f /vagrant/webapp/webapp-ingress.yaml
      kubectl apply -f /vagrant/database-webapp/mongo-config.yaml
      kubectl apply -f /vagrant/database-webapp/mongo-secret.yaml
      kubectl apply -f /vagrant/database-webapp/mongo.yaml
      kubectl apply -f /vagrant/database-webapp/mongo-ingress.yaml
      kubectl apply -f /vagrant/custom-webapp/custom-webapp.yaml
      kubectl apply -f /vagrant/custom-webapp/custom-webapp-ingress.yaml
      kubectl create configmap app3.com --from-file /vagrant/custom-webapp/index.html
      echo "alias 'k'='kubectl'" >> /home/vagrant/.bashrc
    SHELL
  end
end
