# ---------------------------------------------------------------------------- #
#                                    Config                                    #
# ---------------------------------------------------------------------------- #
SERVER_VM_NAME = "jrinna"
SERVER_NODE_NAME = "jrinnaS"
SERVER_NODE_IP = "192.168.56.110"

MEM = "4096"
CPUS = "4"

BOX = "bento/debian-12"

# ---------------------------------------------------------------------------- #
#                                    Config                                    #
# ---------------------------------------------------------------------------- #
Vagrant.configure("2") do |config|
  config.vm.box = BOX

# ---------------------------------- Server ---------------------------------- #

  config.vm.define SERVER_VM_NAME do |server|
    server.vm.hostname = SERVER_NODE_NAME
    server.vm.network "private_network", ip: SERVER_NODE_IP
    server.vm.synced_folder "confs", "/vagrant_shared_folder", type: "virtualbox"
    server.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      vb.gui = false
      
      # Customize the amount of memory on the VM:
      vb.memory = MEM
      vb.cpus = CPUS
      vb.name = SERVER_NODE_NAME
    end
    
    server.vm.provision "shell", inline: <<-SHELL
      # Installing k3s
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --write-kubeconfig-mode 644 --node-ip=#{SERVER_NODE_IP}" sh -s -
      
      # Creating kubectl alias
      echo "alias 'k'='kubectl'" >> /home/vagrant/.bashrc

      # Creating config map for cutom site volume
      kubectl create configmap custom-site-configmap --from-file /vagrant_shared_folder/index.html

      # applying the differente config and secret
      kubectl apply -f /vagrant_shared_folder/mongo-secret.yaml
      kubectl apply -f /vagrant_shared_folder/mongo-config.yaml
      kubectl apply -f /vagrant_shared_folder/ingress.yaml
      # ---------------------------------------------------------------------------- #

      # deploying the 3 app
      # app1 : custom website
      # app2 : nashandra website link to app3
      # app3 : mongodb
      kubectl apply -f /vagrant_shared_folder/custom-site-deployement.yaml
      kubectl apply -f /vagrant_shared_folder/website-deployement.yaml
      kubectl apply -f /vagrant_shared_folder/mongo-deployement.yaml
    SHELL
  end
end
