require 'fileutils'

# Create vagrant_shared_space directory if it doesn't exist
FileUtils.mkdir_p 'vagrant_shared_space' unless File.exist?('vagrant_shared_space')

# ---------------------------------------------------------------------------- #
#                                    Config                                    #
# ---------------------------------------------------------------------------- #
SERVER_VM_NAME = "jrinna"
SERVER_NODE_NAME = "jrinnaS"
SERVER_NODE_IP = "192.168.56.110"

MEM = "4096"
CPUS = "4"

BOX = "bento/debian-12"

# ---------------------------------------------------------------------------- #
#                                    Config                                    #
# ---------------------------------------------------------------------------- #
Vagrant.configure("2") do |config|
  config.vm.box = BOX

# ---------------------------------- Server ---------------------------------- #

  config.vm.define SERVER_VM_NAME do |server|
    server.vm.hostname = SERVER_NODE_NAME
    server.vm.network "private_network", ip: SERVER_NODE_IP
    server.vm.synced_folder "vagrant_shared_space", "/vagrant_shared_folder", type: "virtualbox"
    server.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      vb.gui = false
      
      # Customize the amount of memory on the VM:
      vb.memory = MEM
      vb.cpus = CPUS
      vb.name = SERVER_NODE_NAME
    end
    
    server.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --write-kubeconfig-mode 644 --node-ip=#{SERVER_NODE_IP}" sh -s -
      echo "alias 'k'='kubectl'" >> /home/vagrant/.bashrc
    SHELL
  end
end
