# ---------------------------------------------------------------------------- #
#                                    Config                                    #
# ---------------------------------------------------------------------------- #
SERVER_VM_NAME = "njaros"
SERVER_NODE_NAME = "jrinnaS"
SERVER_NODE_IP = "192.168.56.110"

WORKER_VM_NAME = "jrinna"
WORKER_NODE_NAME = "jrinnaWS"
WORKER_NODE_IP = "192.168.56.111"

MEM = "1024"
CPUS = "1"

BOX = "bento/debian-12"

# ---------------------------------------------------------------------------- #
#                                    Config                                    #
# ---------------------------------------------------------------------------- #
Vagrant.configure("2") do |config|

  config.vm.box = BOX

# ---------------------------------- Server ---------------------------------- #

  config.vm.define SERVER_VM_NAME do |server|
    server.vm.hostname = SERVER_NODE_NAME
    server.vm.network "private_network", ip: SERVER_NODE_IP, bridge: "eth1"
    server.vm.synced_folder ".", "/vagrant_shared_folder", type: "virtualbox"
    server.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --write-kubeconfig-mode 644 --node-ip=#{SERVER_NODE_IP}" sh -s -
      echo "alias 'k'='kubectl'" >> /home/vagrant/.bashrc
      cp /var/lib/rancher/k3s/server/node-token /vagrant_shared_folder/.token
    SHELL
    
    server.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      vb.gui = false
  
      # Customize the amount of memory on the VM:
      vb.memory = MEM
      vb.cpus = CPUS
      vb.name = SERVER_NODE_NAME
    end
  end

# ---------------------------------- Worker ---------------------------------- #

  config.vm.define WORKER_VM_NAME do |worker|
    worker.vm.hostname = WORKER_NODE_NAME
    worker.vm.network "private_network", ip: WORKER_NODE_IP, bridge: "eth1"
    worker.vm.synced_folder ".", "/vagrant_shared_folder", type: "virtualbox"
    worker.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent --node-ip=#{WORKER_NODE_IP}" K3S_URL=https://#{SERVER_NODE_IP}:6443 K3S_TOKEN=$(cat /vagrant_shared_folder/.token) sh -s -
      echo "alias 'k'='kubectl'" >> /home/vagrant/.bashrc
    SHELL
    
    worker.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      vb.gui = false
    
      # Customize the amount of memory on the VM:
      vb.memory = MEM
      vb.cpus = CPUS
      vb.name = WORKER_NODE_NAME
    end
  end

  # ---------------------------------------------------------------------------- #

end
