# ---------------------------------------------------------------------------- #
#                                    DEFINES                                   #
# ---------------------------------------------------------------------------- #
SERVER_NODE_NAME = "jereverdS"
SERVER_NODE_IP = "192.168.56.110"
WORKER_NODE_NAME = "jrinnaSW"
WORKER_NODE_IP = "192.168.56.111"
MEMORY = "2048"
CPUS = "1"

# ---------------------------------------------------------------------------- #
#                                   VM CONFIG                                  #
# ---------------------------------------------------------------------------- #
Vagrant.configure("2") do |config|

  # ----------------------------------- VM 1 ----------------------------------- #

  config.vm.box = "bento/debian-12"
  config.vm.synced_folder "./", "/shared_folder", create: true
  config.vm.define SERVER_NODE_NAME do |server|
    server.vm.hostname = SERVER_NODE_NAME
    server.vm.network "private_network", ip: SERVER_NODE_IP, bridge: "eth1"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = MEMORY
      vb.cpus = CPUS
    end
    # ---------------------------- k3s installation script --------------------------- #
    server.vm.provision "shell", inline: 
    <<-SHELL
      curl -sfL "https://get.k3s.io" | INSTALL_K3S_EXEC="server --write-kubeconfig-mode 644 --node-ip=#{SERVER_NODE_IP}" sh -s -
      cat /var/lib/rancher/k3s/server/node-token > /shared_folder/.token
    SHELL
  end

  # ----------------------------------- VM 2 ----------------------------------- #

  config.vm.define WORKER_NODE_NAME do |worker|
    worker.vm.hostname = WORKER_NODE_NAME
    worker.vm.network "private_network", ip: WORKER_NODE_IP, bridge: "eth1"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = MEMORY
      vb.cpus = CPUS
    end
    # ---------------------------- k3s installation script --------------------------- #
    worker.vm.provision "shell", inline: 
    <<-SHELL
      curl -sfL "https://get.k3s.io" | INSTALL_K3S_EXEC="agent --node-ip=#{WORKER_NODE_IP}" K3S_URL=https://#{SERVER_NODE_IP}:6443 K3S_TOKEN=$(cat /shared_folder/.token) sh -
    SHELL
  end
end
